### ISSUE TITLE
[BUG] A lot of older images have the wrong date 

### ISSUE THREAD

**Issue by M0-7** [IacobIonut01/Gallery#410] opened 2024-05-06 16:20 UTC
**Describe the bug**
A lot of older images that i have are grouped together in one day, but if i download another gallery app like Aves the images are properly separated into their respective days, months or even years. I'm not even sure about how to start debugging this

**To Reproduce**
1. Scroll down to older years
2. See the images grouped together

**Expected behavior**
The images should be grouped separately into their respective days for a better experience

**Screenshots**
Same image but different date

#### Aves info
![Screenshot_20240506_171502_Aves-2](https://github.com/IacobIonut01/Gallery/assets/135035314/8dfd4907-748c-491b-bcc0-94d1021764a2)

#### Gallery info
![Screenshot_20240506_171526_Gallery](https://github.com/IacobIonut01/Gallery/assets/135035314/53e12dc8-0aa6-4df2-a728-1b14d66d9526)

**Smartphone:**
 - Device: Samsung Z fold *
 - OS: One Ui 6.0 Android 14
 - Version: 2.12

**Comment by Natthias** [comment] 2024-05-07 08:29
sounds like a duplicate of [#107](https://github.com/IacobIonut01/Gallery/issues/107), if so this is not a bug

**Closed as completed** 2024-05-07 11:27 UTC
Labels: bug
