### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by julianfairfax** [IacobIonut01/Gallery#34] opened 2023-04-19 20:27 UTC
I have created an issue for this app to be added to F-Droid: https://gitlab.com/fdroid/rfp/-/issues/2412. Do you oppose this?

**Comment by IacobIonut01** [comment] 2023-04-19 22:13
No, I don't oppose.
Thanks!

**Comment by IacobIonut01** [comment] 2023-05-20 12:55
You can generate one for free on the mapbox website and provide it as a secret in your github actions

**Comment by IzzySoft** [comment] 2023-05-20 20:23
@IacobIonut01 What would work with F-Droid is if it compiled without the key present, and the app would let users enter their own in the app's settings.

**Comment by julianfairfax** [comment] 2023-08-02 22:22
@IacobIonut01, to get this app onto F-Droid, we need one more thing: for you to use an explicit version, rather than [this](https://github.com/IacobIonut01/Gallery/blob/v1/app/build.gradle.kts#L16-L29). I.e., please set `versionCode` to `11065` directly, and update it manually. Variables don't work for F-Droid's update checks.

Also, once this change is made, would it be possible to push a new tag (no need for a release, you can just push a tag like 1.1.0.1 or something very small you won't use again), so that we won't have to wait for the new release in order to add the app to F-Droid?

**Comment by IacobIonut01** [comment] 2023-08-03 06:03
Sure

**Comment by licaon-kter** [comment] 2023-08-09 14:15
Regarding reproducibility ( ref: https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds ) can you confirm @IacobIonut01 that the current APK in https://github.com/IacobIonut01/Gallery/releases/tag/v1.1.0.1 was built from https://github.com/IacobIonut01/Gallery/commit/9b665d2600f45cb595751581ac0bd1dd710fa494 ?

Also, is it possible to make an APK by running `gradle clean` first and then `gradle assembleRelease` ?

**Comment by IacobIonut01** [comment] 2023-08-09 14:18
APKs are built using Github Actions so the assembly is always clean. And yes that apk was built based on that commit ref.

**Comment by licaon-kter** [comment] 2023-08-09 14:23
Small mental note, what happens if `MAPS_TOKEN` is not provided? Or if bogus?

**Comment by IacobIonut01** [comment] 2023-08-09 14:24
Map preview won't be available

**Comment by julianfairfax** [comment] 2023-08-23 14:50
@IacobIonut01 can you try uploading a build from that commit, that doesn't have a `MAPS_TOKEN` set? I bet the reason the reproducible builds isn't working is because they're built without the token, whereas yours are built with it.

**Comment by IacobIonut01** [comment] 2023-08-23 14:52
I'll upload one in a bit

**Comment by julianfairfax** [comment] 2023-08-25 12:12
> I'll upload one in a bit

Have you had the chance to do that yet?

**Comment by IacobIonut01** [comment] 2023-09-15 18:39
Sorry for being so late, check the latest release

**Comment by julianfairfax** [comment] 2023-09-16 07:03
It seems that reproducible builds are now working! I have [requested](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13475#note_1562183306) that Gallery now be merged into F-Droid's repository. Once that is (hopefully) done, I will close this issue.

Please note it will take a few days to a week for Gallery to be built and made available to F-Droid users.

Thank you for working on this app and making its inclusion in F-Droid a possibility!

**Comment by IacobIonut01** [comment] 2023-09-16 08:01
Thanks!

**Comment by licaon-kter** [comment] 2023-09-18 10:42
I've updated the MR recipe... 

But, while versionName can be ignored mostly, versionCode is essential (as used by checkupdate to pull a new update to build), and that was not updated when a new version was Tagged/Released, same `20010` in both [beta](https://github.com/IacobIonut01/Gallery/blob/2.0.0-beta/app/build.gradle.kts#L23) and [beta2](https://github.com/IacobIonut01/Gallery/blob/2.0.0-beta2/app/build.gradle.kts#L23)

Regarding the hosted APK, we can use in the recipe 2 templates, `%v` for versionName and `%c` for versionCode, for constructing the APK we need to download and compare for reproducibility.

Currently, since this recipe is in draft mode basically, the path is `Binaries: https://github.com/IacobIonut01/Gallery/releases/download/2.0.0-beta2/Gallery-2.0.0_b6e73f1.apk` which we can't predictively use. versionName is `2.0.0` and not `2.0.0-beta2` so `%v` can't be used. Also `2.0.0_b6e73f1` can't be constructed as we don't have a template for `short commit hash`.

So, @IacobIonut01 can the hosted APK be put on an easier to parse path? Eg. `https://github.com/IacobIonut01/Gallery/releases/download/2.0.0-20010/Gallery-2.0.0-20010.apk` -> `Binaries: https://github.com/IacobIonut01/Gallery/releases/download/%v-%c/Gallery-%v-%c.apk` or some variation that only uses versionCode and/or versionName

**Comment by licaon-kter** [comment] 2023-09-18 10:48
Not repro, :( https://gitlab.com/fdroid/fdroiddata/-/jobs/5109938376#L456 brb to diff

**Comment by julianfairfax** [comment] 2023-09-18 10:58
> Not repro, :( https://gitlab.com/fdroid/fdroiddata/-/jobs/5109938376#L456 brb to diff

@licaon-kter you need to use the -nomaps APKs. There is none for beta2 at the moment, so it is not repro.

Two solutions:
1. We upload the previous version to F-Droid already
2. @IacobIonut01 uploads a -nomaps APK for beta2 and we can then repro that.

**Comment by IacobIonut01** [comment] 2023-09-18 11:00
Yes to everything, all changes will be live at 6PM (Romanian time). I'm currently at work

**Comment by IacobIonut01** [comment] 2023-09-18 16:06
https://github.com/IacobIonut01/Gallery/releases/tag/2.0.0-20021

**Comment by licaon-kter** [comment] 2023-09-20 08:27
@IacobIonut01 Any chance of using a non-snapshot dependency? As snapshots evolve we cant' be sure that building tomorrow we pickup the exact version, this is bad for reproducibility in general

ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13475#note_1565711232

**Comment by IacobIonut01** [comment] 2023-09-20 08:29
Glide for compose is pretty much the whole base for the app and currently is under developed, so having the latest changes as snapshot was the only was It was updated properly, I'll set a fixed version after I decide to a specific head

**Comment by inson1** [comment] 2023-10-14 06:15
@IacobIonut01 May you then reopen the issuie if it isnt done?

**Comment by julianfairfax** [comment] 2023-10-27 04:30
> Glide for compose is pretty much the whole base for the app and currently is under developed, so having the latest changes as snapshot was the only was It was updated properly, I'll set a fixed version after I decide to a specific head

Now that the app is stable, would you consider doing so?

**Comment by IacobIonut01** [comment] 2023-10-27 04:41
> > Glide for compose is pretty much the whole base for the app and currently is under developed, so having the latest changes as snapshot was the only was It was updated properly, I'll set a fixed version after I decide to a specific head
> 
> Now that the app is stable, would you consider doing so?

Sorry for notifying, the glide version is no longer a snapshot one.
Builds should work fine

Btw, for the no-maps build, I've stripped the internet permission in github actions, so this should be considered as well

**Comment by julianfairfax** [comment] 2023-10-27 05:43
> Btw, for the no-maps build, I've stripped the internet permission in github actions, so this should be considered as well

When you do that, reproducible builds don't work anymore, since they need to download the APK from your repo. Please revert this change and publish a new release. Then I can get your app into F-Droid!

**Comment by IacobIonut01** [comment] 2023-10-27 06:03
The 2.0.0-20070 build will pass reproductibile builds, the change is post release

**Comment by julianfairfax** [comment] 2023-10-27 07:19
Ah, I need to set the tag to the correct one. I'm not sure if what I said is right then. I'll make the needed change later and ask the F-Droid devs about the internet.

**Comment by IzzySoft** [comment] 2023-10-27 07:51
@julianfairfax you're right the APKs would no longer match. But there's a second solution to that: just add to the build recipe what that Github action does, so it should fit again (should that still be an issue). So if you strip the INTERNET permission via a Github action, adding the corresponding `sed /xxx/d` line to the build recipe should work, for example. At least in theory.

**Comment by julianfairfax** [comment] 2023-10-27 08:09
I was referring to the fact that F-Droid cannot download the APK from GitHub without internet. But maybe that's not an issue. I didn't think about your issue. Either way, @IacobIonut01 I'd recommend you revert this change.

**Comment by IacobIonut01** [comment] 2023-10-27 08:11
> I was referring to the fact that F-Droid cannot download the APK from GitHub without internet. But maybe that's not an issue. I didn't think about your issue. Either way, @IacobIonut01 I'd recommend you revert this change.

I'm talking about the Internet permission that is no longer required by the Gallery app to work, nothing about F droid store

**Comment by julianfairfax** [comment] 2023-10-27 08:15
Ah, so the build process itself is allowed internet access? Sorry for the misunderstanding.

**Comment by julianfairfax** [comment] 2023-10-27 08:21
There is one thing you can do for us though: please rename the latest release APKs and remove the commit hash. APK names need to follow this format: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13475/diffs#note_1565711232

From my understanding, once this change is made, the app will build correctly, be reproducible, and be automatically updatable without manual intervention. Thus, it will be merged into F-Droid!

**Comment by IzzySoft** [comment] 2023-10-27 08:53
> APK names need to follow this format

To be more precise: The only "variable elements" that can be used in the APK name are the `versionCode` (`%c`) and `versionName` (`%v`). Everything else must be static. There is no variable for commit-hash, date, whatever – only for those two.

**Comment by IacobIonut01** [comment] 2023-10-27 11:35
> There is one thing you can do for us though: please rename the latest release APKs and remove the commit hash. APK names need to follow this format: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13475/diffs#note_1565711232
> 
> From my understanding, once this change is made, the app will build correctly, be reproducible, and be automatically updatable without manual intervention. Thus, it will be merged into F-Droid!

Done

**Comment by licaon-kter** [comment] 2023-10-27 13:29
@IacobIonut01 so I don't read all the text above, we look at -nomap version yes?

So, if there's no map feature we don't need this perm? https://github.com/IacobIonut01/Gallery/blob/2.0.0-20070/app/src/main/AndroidManifest.xml#L21

which raises the next question, the only difference is this key? https://github.com/IacobIonut01/Gallery/blob/2.0.0-20070/.github/workflows/release.yml#L26

**Comment by licaon-kter** [comment] 2023-10-27 13:42
merged now

regarding INTERNET, maybe both F-Droid recipe and CI here https://github.com/IacobIonut01/Gallery/blob/2.0.0-20070/.github/workflows/release_nomaps.yml#L21 can add a
```
sed -i -e '/android.permission.INTERNET/d' src/main/AndroidManifest.xml
```
to remove it in the next version?

**Comment by IacobIonut01** [comment] 2023-10-27 14:17
> merged now
> 
> regarding INTERNET, maybe both F-Droid recipe and CI here https://github.com/IacobIonut01/Gallery/blob/2.0.0-20070/.github/workflows/release_nomaps.yml#L21 can add a
> 
> ```
> sed -i -e '/android.permission.INTERNET/d' src/main/AndroidManifest.xml
> ```
> 
> to remove it in the next version?

the script required to do so is:
```bash
sed -n '/<uses-permission android:name="android.permission.INTERNET"\/>/!p' app/src/main/AndroidManifest.xml > app/src/main/AndroidManifest2.xml && mv app/src/main/AndroidManifest2.xml app/src/main/AndroidManifest.xml
```

**Comment by IacobIonut01** [comment] 2023-10-27 14:20
> @IacobIonut01 so I don't read all the text above, we look at -nomap version yes?
> 
> So, if there's no map feature we don't need this perm? https://github.com/IacobIonut01/Gallery/blob/2.0.0-20070/app/src/main/AndroidManifest.xml#L21
> 
> which raises the next question, the only difference is this key? https://github.com/IacobIonut01/Gallery/blob/2.0.0-20070/.github/workflows/release.yml#L26

1. Yeah, that permission is useless for no-maps version
2. Between normal and no-maps version for 2.0.0-20070 only difference is that MAPS_TOKEN, after 20070, the difference would be MAPS_TOKEN + removed INTERNET permission as requested in #206

**Comment by licaon-kter** [comment] 2023-10-27 14:45
@IacobIonut01 thanks, do ping us to update the recipe before tagging next release

**Comment by IacobIonut01** [comment] 2023-11-01 17:18
@licaon-kter just made a new release

**Comment by julianfairfax** [comment] 2023-11-01 17:32
> @licaon-kter just made a new release

Unless you broke something, you don't need to tell us about new releases. The F-Droid bot will pickup your updates automatically.

**Comment by IacobIonut01** [comment] 2023-11-01 17:34
> > merged now
> > regarding INTERNET, maybe both F-Droid recipe and CI here https://github.com/IacobIonut01/Gallery/blob/2.0.0-20070/.github/workflows/release_nomaps.yml#L21 can add a
> > ```
> > sed -i -e '/android.permission.INTERNET/d' src/main/AndroidManifest.xml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to remove it in the next version?
> 
> the script required to do so is:
> 
> ```shell
> sed -n '/<uses-permission android:name="android.permission.INTERNET"\/>/!p' app/src/main/AndroidManifest.xml > app/src/main/AndroidManifest2.xml && mv app/src/main/AndroidManifest2.xml app/src/main/AndroidManifest.xml
> ```

this one

**Comment by linsui** [comment] 2023-11-02 07:51
Updated.

**Closed** 2023-11-11 14:05 UTC

**Comment by IzzySoft** [comment] 2023-11-21 01:44
Congrats to reaching F-Droid! As your app is still in my repo too, I just wonder: Your Readme links here, but not to F-Droid. What are your plans there? Usually I'd remove it from my repo at this point, so you'd replace the shield with F-Droid's. That OK with you, @IacobIonut01?

**Comment by IacobIonut01** [comment] 2023-11-21 21:02
> Congrats to reaching F-Droid! As your app is still in my repo too, I just wonder: Your Readme links here, but not to F-Droid. What are your plans there? Usually I'd remove it from my repo at this point, so you'd replace the shield with F-Droid's. That OK with you, @IacobIonut01?

Yeah that's ok, do you have any link for a F-Droid chip/banner for README? I'll update the fastlane folder as well by the end of the week, things got quite busy with uni and work

**Comment by IzzySoft** [comment] 2023-11-21 21:37
> do you have any link for a F-Droid chip/banner for README?

I'd need to search. There was some place those things are stored at F-Droid… Ah, there: https://gitlab.com/fdroid/artwork (check the readme, it states something on "how to use" etc).

> things got quite busy with uni and work

Understood, no need to hurry. If it takes a week, it takes a week. Or two. Just give me a ping please when ready :smiley: Thanks!

**Comment by inson1** [comment] 2024-02-05 21:47
it should be automatic
but it seems that it was updated few hours ago and in december, but it isnt updated on the website and it isnt even in weekly post
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.dot.gallery.yml
@licaon-kter iits bug or it didnt build right?

**Comment by inson1** [comment] 2024-02-05 21:55
pipeline in december failed

**Comment by IacobIonut01** [comment] 2024-02-05 21:56
It was fixed on my side

**Comment by inson1** [comment] 2024-02-05 22:00
then I guess we need to wait for this release

**Comment by licaon-kter** [comment] 2024-02-05 22:58
> but it seems that it was updated few hours ago

Well... https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by licaon-kter** [comment] 2024-02-06 12:04
was picked up today https://gitlab.com/fdroid/fdroiddata/-/commit/e69864534a952c613af44fc888483ade72e479e1

**Comment by IacobIonut01** [comment] 2024-02-06 12:15
Thanks!

**Comment by licaon-kter** [comment] 2024-02-08 08:51
Can you name the apk ( https://gitlab.com/fdroid/fdroiddata/-/jobs/6123193580#L505 ) here: https://github.com/IacobIonut01/Gallery/releases/tag/2.1.0-21009 consistently as you did in the past, eg.  `2.1.0-21009/Gallery-2.1.0-21009-nomaps.apk` ? No underscores :)

**Comment by IacobIonut01** [comment] 2024-02-08 09:00
Also, the screenshots are not updated, the new ones are in the fastlane folder

**Comment by licaon-kter** [comment] 2024-02-08 09:17
This cycle will build 21000 and once published it will show the new screenshots
